### PR TITLE
for x from y

### PR DESCRIPTION
**Pull request by benekastah**
```
for x from y, fn()
```

Compiles to:

```
var x, _a;

for (x in y) {
    if (!y.hasOwnProperty(x)) continue;
    _a = y[x];
    fn();
}
```

### CODE REVIEW

**Comment by weepy** [comment]
very nice well done :-) -- a couple of things: 
- I'd like to see it added to one on of the expectations in /expectations
  
  you can run them all by doing
  
  bin/expect
  
  or just one by doing
  
  bin/expect expectations/myfile
- one of the things that Kaffeine does is try to maintain the line-for-line so really your example would all be one line : 

<pre>
var x, _a; for (x in y) { if (!y.hasOwnProperty(x)) continue; _a = y[x]; fn(); }
</pre>

- what's the purpose of _a? 
- we need to handle multiple calls to y if it was a complex value e.g. pull()
  
  <pre>
  _a = pull(); for (x in _a) {
  if (!_a.hasOwnProperty(x)) continue;
  fn();
  }
  </pre>

**Comment by benekastah** [comment]
K. Finished everything but the expectations. Should be done tomorrow.

**Comment by benekastah** [comment]
K. All done and ready for you to look at.

**Comment by weepy** [comment]
awesome - i see you've fixed a problem with my logic too .  I think we also need an expectation for :

<pre>
for(x from y()) {
  ... 
}
</pre>

**Comment by benekastah** [comment]
Yes, good point. I'll take care of it.

**Comment by weepy** [comment]
is this ready to merge ?

**Comment by benekastah** [comment]
Sorry, should have made a note of this. But no. All the expectations pass, but I tried using it in a node app I'm doing and it causes an error. The error always happens right before the loop. I don't get it. If you're curious, this is the error message:

```
Error at position:  [ 1, 0 ] in plugin:  extend_for
of file:  /Users/Paul/dev/js/node/config/settings.k
//*
^

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Cannot read property 'next' of undefined
    at word.<anonymous> (/usr/local/lib/node_modules/kaffeine/lib/plugins/extend_for.js:29:17)
    at word.each (/usr/local/lib/node_modules/kaffeine/lib/token.js:342:21)
    at Kaffeine.<anonymous> (/usr/local/lib/node_modules/kaffeine/lib/plugins/extend_for.js:4:10)
    at Kaffeine.runPlugins (/usr/local/lib/node_modules/kaffeine/lib/index.js:96:14)
    at Kaffeine.compile (/usr/local/lib/node_modules/kaffeine/lib/index.js:26:19)
    at Object..k (/usr/local/lib/node_modules/kaffeine/lib/index.js:145:36)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at require (module.js:351:19)
    at Object.<anonymous> (/Users/Paul/dev/js/node/core/server.k (compiled):4:12)
```

Any thoughts?

**Comment by weepy** [comment]
can u paste the extend_for plugin and the script that causes the error ?

**Comment by benekastah** [comment]
extend_for.js

``` javascript
var Token = require("../token");
module.exports = function(stream) {

  stream.each(function() {
    Token.current_token = this

    if(this.keyword && this.text == "for") { 
      var text = "",
          bracket = this.next,
          skip = false,
          toks = [], var2, var1, loopWord,
          complex

      var closingBracket = bracket.matching

      bracket.next.find(function() {      
        if(this.next == closingBracket) return true
        if(this.semi) { skip = true; return true }
        if(this.word && (this.text == "in" || this.text == "of" || this.text == "from") ) loopWord = this
        if(this.round) complex = true
        toks.push(this)
      })

      var var1 = toks[0]
      if(toks[1].text == ",") var2 = toks[2]
      if(skip) return closingBracket.next

      if(complex) {
        loopWord.next.next.cacheExpression()
      }

      var expressionText = loopWord.next.next.collectText(closingBracket.prev)          
      if(expressionText.match(/ /)) expressionText = "(" + expressionText +")"
      var iter, val
      var closure = this.findClosure()

      /*function wrapSingleLineBlock() {
        if(!this.block) {
          var pair = Token.bracket.pair("{}")
          closingBracket.after(" ").after(pair.L)
          var nl = 2
          var indent = brace.indent()

          var next = pair.L.nextNW()
          if(next.block) {
            var tok = next.block.matching
            if(tok.next.whitespace)
              tok = tok.next
          }
          else if(next.bracelessBlock) {
            var tok = next.bracelessBlock.end
            if(tok.next.whitespace)
              tok = tok.next
          }
          else {
            var tok = closingBracket.find(function() {
              if(this.newline) nl--
              if(nl == 0) return true
            })
          }

          tok.after(pair.R)
          if(indent)
            pair.R.before(indent)
          pair.R.after("\n")
          pair.L.updateBlock()
        }
      }*/

      var brace = bracket.matching.find(function() { if(this.curly) return true })

      if(loopWord.text == "in") { 
        if(!var2) return // nothing to do !

        brace.implied = false
        brace.matching.implied = false

        var2.prev.remove(var2) 
        iter = var1.text
        val = var2.text
        closure.vars[iter] = true
        closure.vars[val] = true

      } else if (loopWord.text == "of") {
        brace.implied = false
        brace.matching.implied = false

        bracket.next.remove(closingBracket.prev)
        iter = var2 ? var2.text : closure.getUnusedVar()

        val = var1.text
        closure.vars[iter] = true
        closure.vars[val] = true

        var length;
        closure.vars[length = closure.getUnusedVar()] = true

        var string = iter + " = 0, " + length + " = " + expressionText + ".length; " + iter + " < " + length + "; " + iter + "++"
        bracket.after(string)

      } else {
        brace.implied = false
        brace.matching.implied = false

        bracket.next.remove(closingBracket.prev)

        if (var2)
          var2.prev.remove(var2)
        iter = var1.text
        closure.vars[iter] = true

        if (var2) {
          val = var2.text
          closure.vars[val] = true
        }

        var string = iter + " in " + expressionText
        bracket.after(string)
      }

      var text = ''
      text += loopWord.text == "from" ? "if (!" + (complex ? "_xpr" : expressionText) + ".hasOwnProperty(" + iter + ")) continue;" : ''
      text += val ? " "/* + this.indent()*/ + val + " = " + (complex ? "_xpr" : expressionText) + "[" + iter + "];" : ''

      this.block.after(text)

      return 
    }
  })
}
```

settings.k (script that causes error)

```
base_settings = require('../core/base_settings')

for name, value from base_settings {
   exports[name] = value
}

/* These settings represent defaults that can be overridden as needed.
exports.VIEWSDIR = "#{exports.APPROOT}/views"
exports.STATICDIR = "#{exports.APPROOT}/public"
//*/

// Options for fugue. Only used in production or test
exports.PORT = 7000
exports.WORKERS = 1
exports.HOST = null
```

base_settings.k

```

exports.APPROOT = process.cwd().replace /\/config$/, ''
exports.VIEWSDIR = "#{exports.APPROOT}/views"
exports.STATICDIR = "#{exports.APPROOT}/public"
exports.ENVIRONMENT = process.env.NODE_ENV || :development
```

**Comment by weepy** [comment]
maybe there's something funky with the line starting:

//*/

?

best thing to do is try reducing the example to the minimum that breaks it -
see if u can figure out which line is causing the problem .  then you should
add this to the expectations ^_^

**Comment by benekastah** [comment]
K. Tomorrow then ;)

**Comment by benekastah** [comment]
It's ready to go!

**Pull request merged**
