### PR TITLE
Add missing optparse dep

### PR DESCRIPTION
**Pull request by felixge**
Just tried out kaffeine for the first time, got got this error after installing with npm install -g kaffeine:

```
$ kaffeine

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'optparse'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/kaffeine/lib/command.js:4:22)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
```

The attached patch should fix this.

I'd also love to chat about kaffeine at some point, after having tried out coffeescript, I seriously consider giving this a try. Compatibility with JS, matching line number and the bang syntax are just awesome.

### CODE REVIEW

**Comment by weepy** [comment]
Hey - a chat would be great. I'm glad u dig it as a project - I think it's great too ! --> but it's been nearly impossible to get any of the CoffeeScript fanboys to take notice ! 
I've been using it on a couple of production sites - and have found it a breeze. As I said on the other ticket - the cmdline has been broken for a while as I've been using the API - but I'll be able to fix it next week. Cheers

**Comment by felixge** [comment]
> Hey - a chat would be great. I'm glad u dig it as a project - I think it's great too ! --> but it's been nearly impossible to get any of the CoffeeScript fanboys to take notice !

Fuck them. This is a much better approach. I like coffeescript, but it would be really hard for me to integrate it into existing projects without rewriting. And I really hate the screwed line numbers.

I'm not sure yet if I'm willing to use an enhanced flavor of JS, but if I do, this is the best I've seen.

**Comment by weepy** [comment]
Indeed - the linenumber preservation means you can run the files directly without a compilation step as you know any problems you'll get the right linenumber in the error output.

**Comment by ghost** [comment]
Any news on this?

**Comment by weepy** [comment]
on my list - i've been backed up a little

**Comment by weepy** [comment]
closing

**Pull request closed without merging**
